export const ADD_POST_TYPE = 'ADD_POST';
export const UPDATE_POST_FORM_VALUE_TYPE = 'UPDATE-POST-FORM-VALUE';
export const ADD_MESSAGE_TYPE = 'ADD-MESSAGE';
export const UPDATE_MESSAGE_FORM_VALUE_TYPE = 'UPDATE-MESSAGE-FORM-VALUE';
